export { default as grassImg } from './grass.jpg'
export { default as glassImg } from './glass.png'
export { default as dirtImg } from './dirt.jpg'
export { default as logImg } from './log.jpg'
export { default as woodImg } from './wood.png'
